---
# ECR
- region: us-east-2
  resource_name: ANCHORE-ECR
  template_file: anchore_ecr.yml
  parameters:
    Environment: DEMO
    AppRepoName: demo/anchore-engine
    TestImageRepoName: tested/nginx
    ImageTag: '1.0'
    